[package]
name = "loci-backend-candle"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
loci-protocol = { path = "../protocol" }
loci-gguf = { path = "../gguf" }
loci-kernels-llama = { path = "../kernels-llama" }
candle-core = { git = "https://github.com/huggingface/candle", package = "candle-core" }
