#!/bin/bash
# Loci Phase 3: iOS Universal Library 构建脚本
# 生成 universal fat library (arm64 device + arm64/x86_64 simulator)
#
# 使用方法：
# ./scripts/build_ios.sh [release|debug]
#
# 要求：
# - macOS 系统
# - 已安装 Xcode Command Line Tools
# - 已安装 cargo-lipo: cargo install cargo-lipo

set -e  # 遇到错误立即退出

BUILD_MODE="${1:-release}"  # 默认 release 模式
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="${PROJECT_ROOT}/target/ios"

echo "╔══════════════════════════════════════════════╗"
echo "║   Loci iOS Universal Library 构建 (Phase 3)  ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "构建模式: ${BUILD_MODE}"
echo "输出目录: ${OUTPUT_DIR}"
echo ""

# 检查操作系统
if [[ "$OSTYPE" != "darwin"* ]]; then
    echo "❌ 错误: iOS 构建仅支持 macOS 系统"
    exit 1
fi

# 检查 Xcode
if ! command -v xcrun &> /dev/null; then
    echo "❌ 错误: 未安装 Xcode Command Line Tools"
    echo "请执行: xcode-select --install"
    exit 1
fi

# 检查 cargo-lipo
if ! command -v cargo-lipo &> /dev/null; then
    echo "📦 安装 cargo-lipo..."
    cargo install cargo-lipo
fi

# 安装 iOS 编译目标
echo "📦 检查 Rust iOS targets..."
rustup target add aarch64-apple-ios           # 真实设备（iPhone/iPad）
rustup target add aarch64-apple-ios-sim       # Apple Silicon Mac 模拟器
rustup target add x86_64-apple-ios            # Intel Mac 模拟器

# 清理旧产物
rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"

# 构建 Universal Library
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔨 构建 iOS Universal Library"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ "$BUILD_MODE" = "release" ]; then
    cargo lipo --release
    UNIVERSAL_LIB="${PROJECT_ROOT}/target/universal/release/libloci.a"
else
    cargo lipo
    UNIVERSAL_LIB="${PROJECT_ROOT}/target/universal/debug/libloci.a"
fi

# 复制产物
cp "$UNIVERSAL_LIB" "${OUTPUT_DIR}/libloci_universal.a"

# 验证产物
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 产物验证"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ -f "${OUTPUT_DIR}/libloci_universal.a" ]; then
    SIZE=$(du -h "${OUTPUT_DIR}/libloci_universal.a" | cut -f1)
    echo "✅ Universal Library: ${SIZE}"

    # 显示架构信息
    echo ""
    echo "支持的架构："
    lipo -info "${OUTPUT_DIR}/libloci_universal.a"

    echo ""
    echo "详细架构列表："
    lipo -archs "${OUTPUT_DIR}/libloci_universal.a"
else
    echo "❌ 构建失败"
    exit 1
fi

# 生成 C 头文件（用于 Objective-C/Swift 互操作）
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 生成 C 头文件"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

HEADER_FILE="${OUTPUT_DIR}/loci.h"
cat > "$HEADER_FILE" << 'EOF'
/**
 * Loci iOS C Header
 * Auto-generated by build_ios.sh
 */

#ifndef LOCI_H
#define LOCI_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Error codes
#define LOCI_OK 0
#define LOCI_ERR_INVALID_HANDLE -1
#define LOCI_ERR_NULL_POINTER -2
#define LOCI_ERR_INIT_FAILED -3
#define LOCI_ERR_GENERATION_FAILED -4

// Stream callback type
typedef int (*LociStreamCallback)(void* user_data, const char* token, int token_len);

// Core API
void* loci_init(const char* model_path, int n_threads, int n_gpu_layers);
int loci_generate(void* engine, const char* prompt, int max_tokens,
                  char* out_text, int out_len);
int loci_generate_stream(void* engine, const char* prompt, int max_tokens,
                         LociStreamCallback callback, void* user_data);
int loci_destroy(void* engine);
const char* loci_last_error(void);

#ifdef __cplusplus
}
#endif

#endif // LOCI_H
EOF

echo "✅ 头文件: ${HEADER_FILE}"

# 生成 Swift 示例
SWIFT_EXAMPLE="${OUTPUT_DIR}/LociExample.swift"
cat > "$SWIFT_EXAMPLE" << 'EOF'
/**
 * Loci Swift 集成示例
 * 演示如何在 Swift 项目中使用 Loci
 */

import Foundation

class LociEngine {
    private var handle: UnsafeMutableRawPointer?

    init?(modelPath: String, threads: Int32 = -1, gpuLayers: Int32 = -1) {
        handle = loci_init(modelPath, threads, gpuLayers)
        guard handle != nil else { return nil }
    }

    func generate(prompt: String, maxTokens: Int32 = 100) -> String? {
        guard let handle = handle else { return nil }

        var output = [CChar](repeating: 0, count: 4096)
        let result = loci_generate(handle, prompt, maxTokens, &output, 4096)

        guard result == LOCI_OK else { return nil }
        return String(cString: output)
    }

    deinit {
        if let handle = handle {
            loci_destroy(handle)
        }
    }
}

// 使用示例
let engine = LociEngine(modelPath: "/path/to/model.gguf")
if let output = engine?.generate(prompt: "Hello, Loci!") {
    print("Generated: \(output)")
}
EOF

echo "✅ Swift 示例: ${SWIFT_EXAMPLE}"

# 总结
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 iOS 构建完成"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "产物位置: ${OUTPUT_DIR}"
echo ""
echo "集成指南："
echo "1. 将 libloci_universal.a 添加到 Xcode 项目"
echo "2. 将 loci.h 添加到桥接头文件"
echo "3. 在 Build Settings 中添加链接标志："
echo "   -framework Metal -framework Accelerate -framework Foundation"
echo ""
echo "Swift 示例："
echo "cat ${SWIFT_EXAMPLE}"
echo ""
