[package]
name = "loci-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
llama = []

[dependencies]
loci-plugin-api = { path = "../plugin-api" }
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true

[build-dependencies]
bindgen = "0.72"
cc = "1.1"
cmake = "0.1"
